### ISSUE TITLE
What should I do to get the screen to boot successfully?

### ISSUE THREAD

**Issue by Qiaijueqing** [aospm/android_device_generic_sdm845#22]
My phone is pocof1 and AOSP images build successfully, but extract Adreno a630_* firmware binaries from lineage-19.1-20220917-nightly-beryllium-signed.zip and copy to out/target/product/beryllium/vendor/firmware and make vendor.img
Unfortunately, the device will not boot to UI. What should I do to get the screen to boot successfully?

**Comment by calebccff** [comment]
Hi,

When using the prebuilt kernel, I think you need to squash the firmware files using https://github.com/andersson/pil-squasher

You can find pre-processed ones here: https://gitlab.com/sdm845-mainline/firmware-xiaomi-beryllium/-/tree/master/lib/firmware/qcom/sdm845/beryllium

There are a few other reasons why it may not be booting, I don't know if the Poco F1 has been validated with the current prebuilts.

**Comment by Qiaijueqing** [comment]
Sorry to bother you again,
I used the link you provided and the method I searched to test and I got two kinds of errors from the kernel log:
1. Use https://github.com/andersson/pil-squasher to merge a630_* into a630_zap.mbn, the file is extracted from miui_POCOF1Global_V12.0.3.0.QEJMIXM_cf3fccffce_10.0.zip download link https://xiaomifirmwareupdater.com/miui /beryllium/stable/V12.0.3.0.QEJMIXM/
Also got the same error using the preprocessing file available here https://gitlab.com/sdm845-mainline/firmware-xiaomi-beryllium/-/tree/master/lib/firmware/qcom/sdm845/beryllium
Error log:
adb shell dmesg |grep a6

[   13.735234] msm ae00000.mdss: [drm:adreno_request_fw [msm]] loaded qcom/a630_sqe.fw from legacy location
[   13.736045] msm ae00000.mdss: [drm:adreno_request_fw [msm]] loaded qcom/a630_gmu.bin from legacy location
[   13.740319] adreno 5000000.gpu: [drm:a6xx_ucode_init [msm]] *ERROR* a630 SQE ucode is too old. Have version 187 need at least 190
[   13.896833] adreno 5000000.gpu: [drm:a6xx_ucode_init [msm]] *ERROR* a630 SQE ucode is too old. Have version 187 need at least 190

2. Use the file linux-firmware-20220913.tar.gz (sig) download link provided here https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/ The error obtained is

Error log:
adb shell dmesg |grep a6

[   13.871245] msm ae00000.mdss: [drm:adreno_request_fw [msm]] loaded qcom/a630_sqe.fw from legacy location
[   13.875031] msm ae00000.mdss: [drm:adreno_request_fw [msm]] loaded qcom/a630_gmu.bin from legacy location
[   13.879009] adreno 5000000.gpu: [drm:adreno_zap_shader_load [msm]] *ERROR* Unable to load qcom/sdm845/a630_zap.mbn
[   14.012212] adreno 5000000.gpu: [drm:adreno_zap_shader_load [msm]] *ERROR* Unable to load qcom/sdm845/a630_zap.mbn
[   14.126825] adreno 5000000.gpu: [drm:adreno_zap_shader_load [msm]] *ERROR* Unable to load qcom/sdm845/a630_zap.mbn
[   18.838678] adreno 5000000.gpu: [drm:adreno_zap_shader_load [msm]] *ERROR* Unable to load qcom/sdm845/a630_zap.mbn
[   19.839910] msm ae00000.mdss: [drm:a6xx_flush [msm]] *ERROR* timeout waiting for space in ringbuffer 0
[   20.839910] [drm:a6xx_idle [msm]] *ERROR* A630: a6xx_hw_init [msm]: timeout waiting for GPU to idle: status 00800005 irq 00800200 rptr/wptr 12/12
[   20.840400] adreno 5000000.gpu: [drm:a6xx_irq [msm]] *ERROR* gpu fault ring 0 fence 0 status 00800005 rb 000c/000c ib1 0000000000000000/0000 ib2 0000000000000000/0000
[   23.867512] adreno 5000000.gpu: [drm:adreno_zap_shader_load [msm]] *ERROR* Unable to load qcom/sdm845/a630_zap.mbn
[   24.867910] msm ae00000.mdss: [drm:a6xx_flush [msm]] *ERROR* timeout waiting for space in ringbuffer 0

**Comment by calebccff** [comment]
Ah, I understand the problem; the A630 SQE fw (a630_sqe.fw) should be taken from upstream Linux firmware, it's not device specific and only needs to be signed by Qualcomm. The version Xiaomi currently ship is out of date, hence the first error.

The other firmware files, a630_gmu.bin and a63_zap.mbn are device specific however, they need to be taken from a device-specific package. In the case of the second snippet you posted the issue is that either a630_zap.mbn is missing, or it's the upstream version which won't work on beryllium.

You need to use the beryllium specific firmware (like from sdm845-mainline) and supplement it with a630_zap.fw from the upstream linux-firmware repository. That should get you going :)

**Comment by Qiaijueqing** [comment]
Sorry for my low level but I still need to run it successfully
firmware extracted from a running poco f1 device
![BA3}Y9J_UKFY{U}8`2K$0%5](https://user-images.githubusercontent.com/87099269/191025560-a0048498-dbb2-4c40-862d-3f8e119a2272.png)
 Copy directly to out/target/product/beryllium/vendor/firmware ![GFK6WH7_C52FYRGGN72{`GI](https://user-images.githubusercontent.com/87099269/191025798-704aced5-2e91-41ab-b2c6-a6e5e7b988cb.png)
After compiling, flash into the poco f1 device *ERROR* a630 SQE ucode is too old. Have version 187 need at least 190 
After replacing the new version a630_sqe.fw, the prompt error is still *ERROR* Unable to load qcom/sdm845/a630_zap.mbn
How can I see if a630_zap.mbn is correct, did I provide the wrong location, or is it loaded inside the kernel?

Is there a successfully compiled and runnable image file?

**Comment by calebccff** [comment]
> ERROR Unable to load qcom/sdm845/a630_zap.mbn

the firmware needs to be in `$FIRMWARE_DIR/qcom/sdm845`, see the layout used in the the firmware-xiaomi-beryllium repo

in the case of the repo, `FIRMWARE_DIR=lib/firmware`, for Android/AOSPM `FIRMWARE_DIR=/vendor/firmware`

cline the repo, copy the contents of lib/firmware to the vendor/firmware directory in your screenshot, then add a630_sqe.fw to the same qcom/sdm845 subdir.

**Comment by Qiaijueqing** [comment]
![7_4 PR5K5{SVOQ4Q_ IZBIT](https://user-images.githubusercontent.com/87099269/191036819-2dadfac9-f103-4b16-8b73-2430c62f8727.png)
Thank you for your help, the problem of a630* loading has been solved.

The reason is that there is a problem with the compiled directory structure. Secondly, the problem of file extraction is not in line with the current device.
But the device cannot boot to the screen. Is the screen driver incompatible? My screen is the first type of EBBG. Should I provide the corresponding driver file and how to obtain the driver file? Have a relevant link?

Know your panel variant
There are two variants of the Xiaomi Poco F1 with different display panels and touchscreens.

1. EBBG Panel (and Focaltech touchscreen) - dsi_ebbg_fhd_ft8719_video_display

2. Tianma Panel (and Novatek touchscreen) - dsi_tianma_fhd_nt36672a_video_display

**Comment by calebccff** [comment]
by default both DTBs will be appended to the kernel, the phones bootloader will pick the first one. you need to delete the one which isn't your variant in the prebuilt-kernel directory. this is a bit of a hack currently

**Comment by Qiaijueqing** [comment]
Forgive my comprehension,
I don't know the directory structure of the source code, but I will compile and modify it according to the instructions.
How should I do it? For example, the file in that directory is driven, should I delete that file?

**Comment by calebccff** [comment]
if you own an EBBG device, delete this file: https://github.com/aospm/android_device_generic_sdm845/blob/main/shared/prebuilt-kernel/android-mainline/sdm845-xiaomi-beryllium-tianma.dtb

under device/generic/sdm845

if you have the tianma variant, delete the -ebbg file. Once that is done, delete the boot image and run make again.

**Comment by Qiaijueqing** [comment]
Feel sorry，
The previous compilation was cloned from pundiramit. It is an old compilation introduction. It can be compiled successfully and booted, but the screen is not displayed, but there is no sdm845-xiaomi-beryllium-tianma.dtb in the directory structure.
Replace the clone aospm compiled successfully. There is sdm845-xiaomi-beryllium-tianma.dtb in the directory structure, but it will automatically enter fastboot mode after booting.
What is this willing to cause? How do I troubleshoot changes

**Comment by Qiaijueqing** [comment]
编译后刷入开机直接进入fastboot模式，没有任何日志我该如何排查错误？这是拉取的最新代码修改了什么造成的？
