### ISSUE TITLE
beryllium  it cannot run the screen ui, only the kernel can run

### ISSUE THREAD

**Issue by Qiaijueqing** [aospm/android_device_generic_sdm845#25]
close

**Comment by Qiaijueqing** [comment]
Is the aospm wiki's aosp compilation instructions and gki kernel compilation instructions outdated and unavailable? I compiled aosp successfully and the one plus 6 can run, but there is no sound, there is a blurry blue screen when charging, and the gki kernel cannot be customized. I want to ask for help but I can't. How to deal with Qing, I can't access OFTC, I'm very helpless

After poco f1 is compiled, the screen ui cannot be run. It is also according to the same compilation instructions. This gki kernel compilation cannot pass the compilation. The 13 kernel uses the Bazel to build the kernel aospm. The gki kernel still uses the Android 12 kernel compilation method. I I don't know if this is the difference?

Can update the wiki compilation instructions or provide more introductory guidance, so that more people can understand, accept and participate in

**Comment by Qiaijueqing** [comment]
Through my own exploration and compilation test, I roughly determine that the location is the kernel startup and the screen driver is not loaded. The mainline contains two screen driver files, tianma and ebbg. The upstream does not contain the above files. How should I compile, add or modify the above files? Is it necessary? Compile the GKI kernel yourself to achieve?

**Comment by pundiramit** [comment]
@Qiaijueqing try my fork from here https://github.com/pundiramit/linux/commits/beryllium-mainline

Build kernel -->
$ make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- beryllium_defconfig
$ cp arch/arm64/boot/Image.gz arch/arm64/boot/dts/qcom/sdm845-xiaomi-beryllium.dtb $AOSP/device/generic/sdm845/shared/prebuilt-kernel/android-upstream/

Build AOSP -->
$ cd $AOSP
$ . build/envsetup.sh
$ lunch beryllium-userdebug
$ make TARGET_KERNEL_USE=upstream -j`nproc`

Flash system, vendor, boot and userdata images. If you have the firmware files copied correctly then these images should boot to UI for you. I have tested these on PocoF1 devices with Tianma display panel.

**Comment by Qiaijueqing** [comment]
@pundiramit  I will try it again, I now think that the ebbg screen cannot be started due to my firmware files. Only the kernel works. I don't know if my firmware files and directory structure are correct. down? Last used source: https://gitlab.com/sdm845-mainline/firmware-xiaomi-beryllium/-/tree/master/lib/firmware
There are several branches here but I am not sure which one should be used and how they differ

**Comment by Qiaijueqing** [comment]
@pundiramit  I successfully built the kernel and successfully replaced the aosp kernel file, and then successfully compiled aosp. What I get now is that the kernel running screen does not run. It should be a problem with the firmware file or the directory structure. The firmware a630* I extracted before did not have these contents, and then I used the files from the website: https://gitlab.com/sdm845- mainline/firmware-xiaomi-beryllium, the problem should be here, the firmware of OnePlus 6 is also from the successful startup screen after this replacement, is the poco f1 firmware directory structure the same as the website? Or is there something missing? How should I extract or Where to look, forgive my ignorance!
![52QDW)S{{K8SG{_W%2T51$E](https://user-images.githubusercontent.com/87099269/192603847-4d0448f2-79c5-4fcd-865e-2019718a308c.png)
![} A{EC_5 G3_XKC6NAI~@$S](https://user-images.githubusercontent.com/87099269/192603853-5c4b7770-26e8-4977-9b03-ef654642de12.png)

**Comment by Qiaijueqing** [comment]
@pundiramit  After slowly searching and trying, I know how to extract the synthetic files, but there are many files in the source image. I am very confused about the firmware directory files, how to define the directory structure and which files are required by aosp. Where is the code clearly defined?

**Comment by pundiramit** [comment]
My tree wont work as is on your EBBG variant because it doesn't have the required driver and DT support. May I suggest you check with @joelselvaraj if you are missing any EBBG patches/fixes from display point of view.

I have copied my adreno firmware binaries in:
$ find out/target/product/beryllium/ -iname a630*
vendor/firmware/a630_gmu.bin
vendor/firmware/a630_zap.b00
vendor/firmware/a630_zap.mbn
vendor/firmware/a630_zap.elf
vendor/firmware/a630_zap.b01
vendor/firmware/a630_zap.b02
vendor/firmware/a630_sqe.fw
vendor/firmware/a630_zap.mdt
vendor/firmware/qcom/sdm845/a630_gmu.bin
vendor/firmware/qcom/sdm845/a630_zap.b00
vendor/firmware/qcom/sdm845/a630_zap.mbn
vendor/firmware/qcom/sdm845/a630_zap.elf
vendor/firmware/qcom/sdm845/a630_zap.b01
vendor/firmware/qcom/sdm845/a630_zap.b02
vendor/firmware/qcom/sdm845/a630_sqe.fw
vendor/firmware/qcom/sdm845/a630_zap.mdt

If you still run into display issues then please share the logcat dump.

**Comment by Qiaijueqing** [comment]
I will follow this directory structure immediately, thank you for the guidance, if it still doesn't work, I will upload the logcat later.

**Comment by Qiaijueqing** [comment]
@pundiramit  I placed the firmware according to what you know, but the screen still doesn't work. The log after booting up is as follows:


[dmesg.log](https://github.com/aospm/android_device_generic_sdm845/files/9665378/dmesg.log)

**Comment by Qiaijueqing** [comment]
@pundiramit  I checked the kernel source code and found that the firmware location 6.0 is different from the previous one. I changed the firmware and put it in a new location and turned on the ebbg screen driver. After compiling, it will restart to the kernel and then automatically restart. The screen still does not work. The kernel defaults to only When compiling the Tianma screen driver, I forbid the Tianma driver to turn on the ebbg driver. Do I need to modify other places?

**Comment by pundiramit** [comment]
@Qiaijueqing see if you have the ebbg driver patches in your tree https://lore.kernel.org/lkml/20220806210220.31565-1-joelselvaraj.oss@gmail.com/

**Comment by pundiramit** [comment]
@Qiaijueqing Sorry about not pointing you to the updated firmware loading path changes in v6.0. Can you share the latest logcat dump with firmware and driver changes.

**Comment by Qiaijueqing** [comment]
@pundiramit I haven't looked at the source code of the kernel carefully, but I just looked at it roughly. My approach may be wrong. This is what I guessed and tried. I will continue to study hard. I'll try again to make the changes and sort out the relevant files and logcat files to upload later.

**Comment by Qiaijueqing** [comment]
@pundiramit  Thank you for your guidance, no need to do other extra operations, pull the code, the ebbg screen can be started after patching, the firmware is also the same as before without any changes, just moved the directory, but the new problem is that the touch screen does not work, is it also Missing touchscreen patch? I'm a novice and don't understand these very well, where should I go to find these related patches?

Latest kernel boot log:
[dmesg.log](https://github.com/aospm/android_device_generic_sdm845/files/9687238/dmesg.log)
