### ISSUE TITLE
Can update the wiki compilation instructions or provide more introductory guidance

### ISSUE THREAD

**Issue by Qiaijueqing** [aospm/android_device_generic_sdm845#26]
closed

**Comment by calebccff** [comment]
Hi there,

Please don't keep opening new issues, rather lets discuss in a single one if other platforms don't work for you, #25.

The wiki is publically editable - currently it contains only what is within the scope of the project, work on building GKI kernels may happen in the future, in which case I expect the wiki would be updated.
